name: Update Timer JSON via Issues
on:
  issues:
    types: [opened]
jobs:
  update-timer:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'reset' || github.event.issue.title == 'minus4'
    steps:
      - uses: actions/checkout@v4
      - name: Read and modify time.json
        run: |
          NOW=$(date +%s)
          if [[ "${{ github.event.issue.title }}" == "reset" ]]; then
            NEW_END=$((NOW + 32*3600))
          else
            END=$(jq .end_time time.json)
            NEW_END=$((END - 4*3600))
          fi
          echo "{ \"end_time\": $NEW_END }" > time.json
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add time.json
          git commit -m "Update time.yml via ${{ github.event.issue.title }}"
          git push
